'use strict';function t(f,a,b,d){f.A.kc(f.$a,a,b,d,void 0)}function D(f,a,b,d){f.A.ra?t(f,a,b,d):f.A.ff()._OnMessageFromDOM({type:"event",component:f.$a,handler:a,dispatchOpts:d||null,data:b,responseId:null})}function F(f,a,b){f.A.C(f.$a,a,b)}function H(f,a){for(const [b,d]of a)F(f,b,d)}function I(f){f.Pb||(f.A.Re(f.ae),f.Pb=!0)}window.Ca=class{constructor(f,a){this.A=f;this.$a=a;this.Pb=!1;this.ae=()=>this.ua()}dd(){}ua(){}};function L(f){-1!==f.Pa&&(self.clearTimeout(f.Pa),f.Pa=-1)}
window.Ie=class{constructor(f,a){this.Kc=f;this.tg=a;this.Pa=-1;this.Qb=-Infinity;this.be=()=>{this.Pa=-1;this.Qb=Date.now();this.fb=!0;this.Kc();this.fb=!1};this.Jd=this.fb=!1}c(){L(this);this.be=this.Kc=null}};"use strict";function M(f,a){F(f,"get-element",b=>{const d=f.ca.get(b.elementId);return a(d,b)})}
window.Mg=class extends self.Ca{constructor(f,a){super(f,a);this.ca=new Map;this.Jc=!0;H(this,[["create",()=>{throw Error("required override");}],["destroy",b=>{{b=b.elementId;const d=this.ca.get(b);this.Jc&&d.parentElement.removeChild(d);this.ca.delete(b)}}],["set-visible",b=>{this.Jc&&(this.ca.get(b.elementId).style.display=b.isVisible?"":"none")}],["update-position",b=>{if(this.Jc){var d=this.ca.get(b.elementId);d.style.left=b.left+"px";d.style.top=b.top+"px";d.style.width=b.width+"px";d.style.height=
b.height+"px";b=b.fontSize;null!==b&&(d.style.fontSize=b+"em")}}],["update-state",b=>{this.ca.get(b.elementId);throw Error("required override");}],["focus",b=>this.Dc(b)],["set-css-style",b=>{this.ca.get(b.elementId).style[b.prop]=b.val}],["set-attribute",b=>{this.ca.get(b.elementId).setAttribute(b.name,b.val)}],["remove-attribute",b=>{this.ca.get(b.elementId).removeAttribute(b.name)}]]);M(this,b=>b)}Dc(f){var a=this.ca.get(f.elementId);f.focus?a.focus():a.blur()}};"use strict";
{const f=/(iphone|ipod|ipad|macos|macintosh|mac os x)/i.test(navigator.userAgent);let a=0;function b(h){const c=document.createElement("script");c.async=!1;c.type="module";return h.Dg?new Promise(k=>{const l="c3_resolve_"+a;++a;self[l]=k;c.textContent=h.Gg+`\n\nself["${l}"]();`;document.head.appendChild(c)}):new Promise((k,l)=>{c.onload=k;c.onerror=l;c.src=h;document.head.appendChild(c)})}let d=!1,g=!1;function m(){if(!d){try{new Worker("blob://",{get type(){g=!0}})}catch(h){}d=!0}return g}let p=
new Audio;const x={"audio/webm; codecs=opus":!!p.canPlayType("audio/webm; codecs=opus"),"audio/ogg; codecs=opus":!!p.canPlayType("audio/ogg; codecs=opus"),"audio/webm; codecs=vorbis":!!p.canPlayType("audio/webm; codecs=vorbis"),"audio/ogg; codecs=vorbis":!!p.canPlayType("audio/ogg; codecs=vorbis"),"audio/mp4":!!p.canPlayType("audio/mp4"),"audio/mpeg":!!p.canPlayType("audio/mpeg")};p=null;async function A(h){h=await B(h);return(new TextDecoder("utf-8")).decode(h)}function B(h){return new Promise((c,
k)=>{const l=new FileReader;l.onload=n=>c(n.target.result);l.onerror=n=>k(n);l.readAsArrayBuffer(h)})}const v=[];let w=0;window.RealFile=window.File;const C=[],G=new Map,y=new Map;let J=0;const E=[];self.runOnStartup=function(h){if("function"!==typeof h)throw Error("runOnStartup called without a function");E.push(h)};const K=new Set(["cordova","playable-ad","instant-games"]);let e=!1;window.ma=class h{constructor(c){this.ra=c.Ig;this.pa=null;this.F="";this.Yb=c.Fg;this.tb={};this.Ia=this.sb=null;
this.Nb=[];this.hb=this.K=this.Na=null;this.Ma=-1;this.yg=()=>this.Ef();this.La=[];this.u=c.ce;!this.ra||"undefined"!==typeof OffscreenCanvas&&navigator.userActivation&&m()||(this.ra=!1);K.has(this.u)&&this.ra&&(console.warn("[C3 runtime] Worker mode is enabled and supported, but is currently disabled in WebViews. Reverting to DOM mode."),this.ra=!1);this.Sb=this.ha=null;"html5"!==this.u&&"playable-ad"!==this.u||"file"!==location.protocol.substr(0,4)||alert("Exported games won't work until you upload them. (When running on the file: protocol, browsers block many features from working for security reasons.)");
this.C("runtime","cordova-fetch-local-file",k=>this.nf(k));this.C("runtime","create-job-worker",()=>this.pf());"cordova"===this.u?document.addEventListener("deviceready",()=>this.wd(c)):this.wd(c)}c(){this.qc();this.pa&&(this.pa=this.pa.onmessage=null);this.sb&&(this.sb.terminate(),this.sb=null);this.Ia&&(this.Ia.c(),this.Ia=null);this.K&&(this.K.parentElement.removeChild(this.K),this.K=null)}md(){return f&&"cordova"===this.u}jc(){return f&&K.has(this.u)||navigator.standalone}async wd(c){"macos-wkwebview"===
this.u&&this.Hc({type:"ready"});if("playable-ad"===this.u){this.ha=self.c3_base64files;this.Sb={};await this.We();for(let l=0,n=c.Qa.length;l<n;++l){var k=c.Qa[l].toLowerCase();this.Sb.hasOwnProperty(k)?c.Qa[l]={Dg:!0,Gg:this.Sb[k]}:this.ha.hasOwnProperty(k)&&(c.Qa[l]=URL.createObjectURL(this.ha[k]))}}c.zg?this.F=c.zg:(k=location.origin,this.F=("null"===k?"file:///":k)+location.pathname,k=this.F.lastIndexOf("/"),-1!==k&&(this.F=this.F.substr(0,k+1)));c.Kg&&(this.tb=c.Kg);k=new MessageChannel;this.pa=
k.port1;this.pa.onmessage=l=>this._OnMessageFromRuntime(l.data);window.c3_addPortMessageHandler&&window.c3_addPortMessageHandler(l=>this.Af(l));this.hb=new self.Ee(this);await N(this.hb);"object"===typeof window.StatusBar&&window.StatusBar.hide();"object"===typeof window.AndroidFullScreen&&window.AndroidFullScreen.immersiveMode();this.ra?await this.hf(c,k.port2):await this.gf(c,k.port2)}tc(c){c=this.tb.hasOwnProperty(c)?this.tb[c]:c.endsWith("/workermain.js")&&this.tb.hasOwnProperty("workermain.js")?
this.tb["workermain.js"]:"playable-ad"===this.u&&this.ha.hasOwnProperty(c.toLowerCase())?this.ha[c.toLowerCase()]:c;c instanceof Blob&&(c=URL.createObjectURL(c));return c}async cc(c,k,l){if(c.startsWith("blob:"))return new Worker(c,l);if(this.md()&&"file:"===location.protocol)return c=await this.ub(this.Yb+c),new Worker(URL.createObjectURL(new Blob([c],{type:"application/javascript"})),l);c=new URL(c,k);if(location.origin!==c.origin){c=await fetch(c);if(!c.ok)throw Error("failed to fetch worker script");
c=await c.blob();return new Worker(URL.createObjectURL(c),l)}return new Worker(c,l)}xa(){return Math.max(window.innerWidth,1)}wa(){return Math.max(window.innerHeight,1)}vd(c){var k=this.hb;return{baseUrl:this.F,windowInnerWidth:this.xa(),windowInnerHeight:this.wa(),devicePixelRatio:window.devicePixelRatio,isFullscreen:h.Ua(),projectData:c.Rg,previewImageBlobs:window.cr_previewImageBlobs||this.ha,previewProjectFileBlobs:window.cr_previewProjectFileBlobs,previewProjectFileSWUrls:window.cr_previewProjectFiles,
swClientId:window.Pg||"",exportType:c.ce,isDebug:-1<self.location.search.indexOf("debug"),ife:!!self.Qg,jobScheduler:{inputPort:k.Qc,outputPort:k.Yc,maxNumWorkers:k.vg},supportedAudioFormats:x,opusWasmScriptUrl:window.cr_opusWasmScriptUrl||this.Yb+"opus.wasm.js",opusWasmBinaryUrl:window.cr_opusWasmBinaryUrl||this.Yb+"opus.wasm.wasm",isiOSCordova:this.md(),isiOSWebView:this.jc(),isFBInstantAvailable:"undefined"!==typeof self.FBInstant}}async hf(c,k){var l=this.tc(c.Jg);this.sb=await this.cc(l,this.F,
{type:"module",name:"Runtime"});this.K=document.createElement("canvas");this.K.style.display="none";l=this.K.transferControlToOffscreen();document.body.appendChild(this.K);window.c3canvas=this.K;this.sb.postMessage(Object.assign(this.vd(c),{type:"init-runtime",isInWorker:!0,messagePort:k,canvas:l,workerDependencyScripts:c.cd||[],engineScripts:c.Qa,projectScripts:c.ee,mainProjectScript:c.de,projectScriptsStatus:self.C3_ProjectScriptsStatus}),[k,l,...O(this.hb)]);this.Nb=C.map(n=>new n(this));this.ud();
self.c3_callFunction=(n,r)=>this.Na.jf(n,r);"preview"===this.u&&(self.goToLastErrorScript=()=>this.kc("runtime","go-to-last-error-script"))}async gf(c,k){this.K=document.createElement("canvas");this.K.style.display="none";document.body.appendChild(this.K);window.c3canvas=this.K;this.Nb=C.map(q=>new q(this));this.ud();var l=c.Qa.map(q=>"string"===typeof q?(new URL(q,this.F)).toString():q);Array.isArray(c.cd)&&l.unshift(...c.cd);l=await Promise.all(l.map(q=>this.xc(q)));await Promise.all(l.map(q=>b(q)));
l=self.C3_ProjectScriptsStatus;const n=c.de,r=c.ee;for(let [q,u]of r)if(u||(u=q),q===n)try{u=await this.xc(u),await b(u),"preview"!==this.u||l[q]||this.Ed(q,"main script did not run to completion")}catch(z){this.Ed(q,z)}else if("scriptsInEvents.js"===q||q.endsWith("/scriptsInEvents.js"))u=await this.xc(u),await b(u);"preview"===this.u&&"object"!==typeof self.Lg.Ng?(this.Gb(),console.error("[C3 runtime] Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax."),
alert("Failed to load JavaScript code used in events. Check all your JavaScript code has valid syntax.")):(c=Object.assign(this.vd(c),{isInWorker:!1,messagePort:k,canvas:this.K,runOnStartupFunctions:E}),this.yd(),this.Ia=self.C3_CreateRuntime(c),await self.C3_InitRuntime(this.Ia,c))}Ed(c,k){this.Gb();console.error(`[Preview] Failed to load project main script (${c}): `,k);alert(`Failed to load project main script (${c}). Check all your JavaScript code has valid syntax. Press F12 and check the console for error details.`)}yd(){this.Gb()}Gb(){const c=
window.Ag;c&&(c.parentElement.removeChild(c),window.Ag=null)}async pf(){const c=await P(this.hb);return{outputPort:c,transferables:[c]}}ff(){if(this.ra)throw Error("not available in worker mode");return this.Ia}kc(c,k,l,n,r){this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:n||null,data:l,responseId:null},r)}nd(c,k,l,n,r){const q=J++,u=new Promise((z,U)=>{y.set(q,{resolve:z,reject:U})});this.pa.postMessage({type:"event",component:c,handler:k,dispatchOpts:n||null,data:l,responseId:q},
r);return u}["_OnMessageFromRuntime"](c){const k=c.type;if("event"===k)return this.uf(c);if("result"===k)this.Hf(c);else if("runtime-ready"===k)this.If();else if("alert-error"===k)this.Gb(),alert(c.message);else if("creating-runtime"===k)this.yd();else throw Error(`unknown message '${k}'`);}uf(c){const k=c.component,l=c.handler,n=c.data,r=c.responseId;if(c=G.get(k))if(c=c.get(l)){var q=null;try{q=c(n)}catch(u){console.error(`Exception in '${k}' handler '${l}':`,u);null!==r&&this.Fb(r,!1,""+u);return}if(null===
r)return q;q&&q.then?q.then(u=>this.Fb(r,!0,u)).catch(u=>{console.error(`Rejection from '${k}' handler '${l}':`,u);this.Fb(r,!1,""+u)}):this.Fb(r,!0,q)}else console.warn(`[DOM] No handler '${l}' for component '${k}'`);else console.warn(`[DOM] No event handlers for component '${k}'`)}Fb(c,k,l){let n;l&&l.transferables&&(n=l.transferables);this.pa.postMessage({type:"result",responseId:c,isOk:k,result:l},n)}Hf(c){const k=c.responseId,l=c.isOk;c=c.result;const n=y.get(k);l?n.resolve(c):n.reject(c);y.delete(k)}C(c,
k,l){let n=G.get(c);n||(n=new Map,G.set(c,n));if(n.has(k))throw Error(`[DOM] Component '${c}' already has handler '${k}'`);n.set(k,l)}static Ra(c){if(C.includes(c))throw Error("DOM handler already added");C.push(c)}ud(){for(const c of this.Nb)if("runtime"===c.$a){this.Na=c;return}throw Error("cannot find runtime DOM handler");}Af(c){this.kc("debugger","message",c)}If(){for(const c of this.Nb)c.dd()}static Ua(){return!!(document.fullscreenElement||document.webkitFullscreenElement||document.mozFullScreenElement||
e)}static Hb(c){e=!!c}Re(c){this.La.push(c);this.Gc()}Uf(c){c=this.La.indexOf(c);if(-1===c)throw Error("invalid callback");this.La.splice(c,1);this.La.length||this.qc()}Gc(){-1===this.Ma&&this.La.length&&(this.Ma=requestAnimationFrame(this.yg))}qc(){-1!==this.Ma&&(cancelAnimationFrame(this.Ma),this.Ma=-1)}Ef(){this.Ma=-1;for(const c of this.La)c();this.Gc()}va(c){this.Na.va(c)}Ea(c){this.Na.Ea(c)}Fc(){this.Na.Fc()}Ab(c){this.Na.Ab(c)}De(){return!!x["audio/webm; codecs=opus"]}async rg(c){c=await this.nd("runtime",
"opus-decode",{arrayBuffer:c},null,[c]);return new Float32Array(c)}Ce(c){return/^(?:[a-z\-]+:)?\/\//.test(c)||"data:"===c.substr(0,5)||"blob:"===c.substr(0,5)}ld(c){return!this.Ce(c)}async xc(c){return"cordova"===this.u&&(c.startsWith("file:")||"file:"===location.protocol&&this.ld(c))?(c.startsWith(this.F)&&(c=c.substr(this.F.length)),c=await this.ub(c),URL.createObjectURL(new Blob([c],{type:"application/javascript"}))):c}async nf(c){const k=c.filename;switch(c.as){case "text":return await this.ve(k);
case "buffer":return await this.ub(k);default:throw Error("unsupported type");}}gd(c){const k=window.cordova.file.applicationDirectory+"www/"+c.toLowerCase();return new Promise((l,n)=>{window.resolveLocalFileSystemURL(k,r=>{r.file(l,n)},n)})}async ve(c){c=await this.gd(c);return await A(c)}rc(){if(v.length&&!(8<=w)){w++;var c=v.shift();this.Xe(c.filename,c.Hg,c.Cg)}}ub(c){return new Promise((k,l)=>{v.push({filename:c,Hg:n=>{w--;this.rc();k(n)},Cg:n=>{w--;this.rc();l(n)}});this.rc()})}async Xe(c,k,
l){try{const n=await this.gd(c),r=await B(n);k(r)}catch(n){l(n)}}Hc(c){if("windows-webview2"===this.u)window.chrome.webview.postMessage(JSON.stringify(c));else if("macos-wkwebview"===this.u)window.webkit.messageHandlers.C3Wrapper.postMessage(JSON.stringify(c));else throw Error("cannot send wrapper message");}async We(){const c=[];for(const [k,l]of Object.entries(this.ha))c.push(this.Ve(k,l));await Promise.all(c)}async Ve(c,k){if("object"===typeof k)this.ha[c]=new Blob([k.str],{type:k.type}),this.Sb[c]=
k.str;else{let l=await this.df(k);l||(l=this.Ze(k));this.ha[c]=l}}async df(c){try{return await (await fetch(c)).blob()}catch(k){return console.warn("Failed to fetch a data: URI. Falling back to a slower workaround. This is probably because the Content Security Policy unnecessarily blocked it. Allow data: URIs in your CSP to avoid this.",k),null}}Ze(c){c=this.Of(c);return this.Ue(c.data,c.Eg)}Of(c){var k=c.indexOf(",");if(0>k)throw new URIError("expected comma in data: uri");var l=c.substring(k+1);
k=c.substring(5,k).split(";");c=k[0]||"";const n=k[2];l="base64"===k[1]||"base64"===n?atob(l):decodeURIComponent(l);return{Eg:c,data:l}}Ue(c,k){var l=c.length;let n=l>>2,r=new Uint8Array(l),q=new Uint32Array(r.buffer,0,n),u,z;for(z=u=0;u<n;++u)q[u]=c.charCodeAt(z++)|c.charCodeAt(z++)<<8|c.charCodeAt(z++)<<16|c.charCodeAt(z++)<<24;for(l&=3;l--;)r[z]=c.charCodeAt(z),++z;return new Blob([r],{type:k})}}}"use strict";
{const f=self.ma;function a(e){return e.sourceCapabilities&&e.sourceCapabilities.firesTouchEvents||e.originalEvent&&e.originalEvent.sourceCapabilities&&e.originalEvent.sourceCapabilities.firesTouchEvents}const b=new Map([["OSLeft","MetaLeft"],["OSRight","MetaRight"]]),d={dispatchRuntimeEvent:!0,dispatchUserScriptEvent:!0},g={dispatchUserScriptEvent:!0},m={dispatchRuntimeEvent:!0};function p(e){return new Promise((h,c)=>{const k=document.createElement("link");k.onload=()=>h(k);k.onerror=l=>c(l);k.rel=
"stylesheet";k.href=e;document.head.appendChild(k)})}function x(e){return new Promise((h,c)=>{const k=new Image;k.onload=()=>h(k);k.onerror=l=>c(l);k.src=e})}async function A(e){e=URL.createObjectURL(e);try{return await x(e)}finally{URL.revokeObjectURL(e)}}function B(e){return new Promise((h,c)=>{let k=new FileReader;k.onload=l=>h(l.target.result);k.onerror=l=>c(l);k.readAsText(e)})}async function v(e,h,c){if(!/firefox/i.test(navigator.userAgent))return await A(e);var k=await B(e);k=(new DOMParser).parseFromString(k,
"image/svg+xml");const l=k.documentElement;if(l.hasAttribute("width")&&l.hasAttribute("height")){const n=l.getAttribute("width"),r=l.getAttribute("height");if(!n.includes("%")&&!r.includes("%"))return await A(e)}l.setAttribute("width",h+"px");l.setAttribute("height",c+"px");k=(new XMLSerializer).serializeToString(k);e=new Blob([k],{type:"image/svg+xml"});return await A(e)}function w(e){do{if(e.parentNode&&e.hasAttribute("contenteditable"))return!0;e=e.parentNode}while(e);return!1}const C=new Set(["input",
"textarea","datalist","select"]),G=new Set(["canvas","body","html"]);function y(e){G.has(e.target.tagName.toLowerCase())&&e.preventDefault()}function J(e){(e.metaKey||e.ctrlKey)&&e.preventDefault()}self.C3_GetSvgImageSize=async function(e){e=await A(e);if(0<e.width&&0<e.height)return[e.width,e.height];{e.style.position="absolute";e.style.left="0px";e.style.top="0px";e.style.visibility="hidden";document.body.appendChild(e);const h=e.getBoundingClientRect();document.body.removeChild(e);return[h.width,
h.height]}};self.C3_RasterSvgImageBlob=async function(e,h,c,k,l){e=await v(e,h,c);const n=document.createElement("canvas");n.width=k;n.height=l;n.getContext("2d").drawImage(e,0,0,h,c);return n};let E=!1;document.addEventListener("pause",()=>E=!0);document.addEventListener("resume",()=>E=!1);function K(){try{return window.parent&&window.parent.document.hasFocus()}catch(e){return!1}}f.Ra(class extends self.Ca{constructor(e){super(e,"runtime");this.Od=!0;this.Oa=-1;this.$c="any";this.Fd=this.Gd=!1;this.Uc=
this.pb=this.za=null;e.C("canvas","update-size",k=>this.Lf(k));e.C("runtime","invoke-download",k=>this.yf(k));e.C("runtime","raster-svg-image",k=>this.Ff(k));e.C("runtime","get-svg-image-size",k=>this.wf(k));e.C("runtime","set-target-orientation",k=>this.Jf(k));e.C("runtime","register-sw",()=>this.Gf());e.C("runtime","post-to-debugger",k=>this.Ad(k));e.C("runtime","go-to-script",k=>this.Ad(k));e.C("runtime","before-start-ticking",()=>this.mf());e.C("runtime","debug-highlight",k=>this.qf(k));e.C("runtime",
"enable-device-orientation",()=>this.Te());e.C("runtime","enable-device-motion",()=>this.Se());e.C("runtime","add-stylesheet",k=>this.lf(k));e.C("runtime","alert",k=>this.yc(k));e.C("runtime","hide-cordova-splash",()=>this.xf());const h=new Set(["input","textarea","datalist"]);window.addEventListener("contextmenu",k=>{const l=k.target;h.has(l.tagName.toLowerCase())||w(l)||k.preventDefault()});const c=e.K;window.addEventListener("selectstart",y);window.addEventListener("gesturehold",y);c.addEventListener("selectstart",
y);c.addEventListener("gesturehold",y);window.addEventListener("touchstart",y,{passive:!1});"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",y,{passive:!1}),c.addEventListener("pointerdown",y)):c.addEventListener("touchstart",y);this.mb=0;window.addEventListener("mousedown",k=>{1===k.button&&k.preventDefault()});window.addEventListener("mousewheel",J,{passive:!1});window.addEventListener("wheel",J,{passive:!1});window.addEventListener("resize",()=>this.Mf());window.addEventListener("fullscreenchange",
()=>this.Wa());window.addEventListener("webkitfullscreenchange",()=>this.Wa());window.addEventListener("mozfullscreenchange",()=>this.Wa());window.addEventListener("fullscreenerror",k=>this.Ac(k));window.addEventListener("webkitfullscreenerror",k=>this.Ac(k));window.addEventListener("mozfullscreenerror",k=>this.Ac(k));e.jc()&&window.addEventListener("focusout",()=>{{const n=document.activeElement;if(n){var k=n.tagName.toLowerCase();var l=new Set("email number password search tel text url".split(" "));
k="textarea"===k?!0:"input"===k?l.has(n.type.toLowerCase()||"text"):w(n)}else k=!1}k||(document.scrollingElement.scrollTop=0)});self.C3WrapperOnMessage=k=>this.Nf(k);this.Ja=new Set;this.Tb=new WeakSet;this.oa=!1}mf(){"cordova"===this.A.u?(document.addEventListener("pause",()=>this.Ec(!0)),document.addEventListener("resume",()=>this.Ec(!1))):document.addEventListener("visibilitychange",()=>this.Ec(document.hidden));return{isSuspended:!(!document.hidden&&!E)}}dd(){window.addEventListener("focus",()=>
this.Ya("window-focus"));window.addEventListener("blur",()=>{this.Ya("window-blur",{parentHasFocus:K()});this.mb=0});window.addEventListener("focusin",h=>{h=h.target;(C.has(h.tagName.toLowerCase())||w(h))&&this.Ya("keyboard-blur")});window.addEventListener("keydown",h=>this.zd("keydown",h));window.addEventListener("keyup",h=>this.zd("keyup",h));window.addEventListener("dblclick",h=>this.Bc("dblclick",h,d));window.addEventListener("wheel",h=>this.Cf(h));"undefined"!==typeof PointerEvent?(window.addEventListener("pointerdown",
h=>{this.uc(h);this.Xa("pointerdown",h)}),this.A.ra&&"undefined"!==typeof window.onpointerrawupdate&&self===self.top?(this.pb=new self.Ie(()=>this.bf(),5),this.pb.Jd=!0,window.addEventListener("pointerrawupdate",h=>this.Df(h))):window.addEventListener("pointermove",h=>this.Xa("pointermove",h)),window.addEventListener("pointerup",h=>this.Xa("pointerup",h)),window.addEventListener("pointercancel",h=>this.Xa("pointercancel",h))):(window.addEventListener("mousedown",h=>{this.uc(h);this.Cc("pointerdown",
h)}),window.addEventListener("mousemove",h=>this.Cc("pointermove",h)),window.addEventListener("mouseup",h=>this.Cc("pointerup",h)),window.addEventListener("touchstart",h=>{this.uc(h);this.Eb("pointerdown",h)}),window.addEventListener("touchmove",h=>this.Eb("pointermove",h)),window.addEventListener("touchend",h=>this.Eb("pointerup",h)),window.addEventListener("touchcancel",h=>this.Eb("pointercancel",h)));const e=()=>this.Fc();window.addEventListener("pointerup",e,!0);window.addEventListener("touchend",
e,!0);window.addEventListener("click",e,!0);window.addEventListener("keydown",e,!0);window.addEventListener("gamepadconnected",e,!0)}Ya(e,h){t(this,e,h||null,m)}xa(){return this.A.xa()}wa(){return this.A.wa()}Mf(){const e=this.xa(),h=this.wa();this.Ya("window-resize",{innerWidth:e,innerHeight:h,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Ua()});this.A.jc()&&(-1!==this.Oa&&clearTimeout(this.Oa),this.Bd(e,h,0))}Vf(e,h,c){-1!==this.Oa&&clearTimeout(this.Oa);this.Oa=setTimeout(()=>this.Bd(e,
h,c),48)}Bd(e,h,c){const k=this.xa(),l=this.wa();this.Oa=-1;k!=e||l!=h?this.Ya("window-resize",{innerWidth:k,innerHeight:l,devicePixelRatio:window.devicePixelRatio,isFullscreen:f.Ua()}):10>c&&this.Vf(k,l,c+1)}Jf(e){this.$c=e.targetOrientation}ng(){const e=this.$c;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(e).catch(h=>console.warn("[Construct 3] Failed to lock orientation: ",h));else try{let h=!1;screen.lockOrientation?h=screen.lockOrientation(e):screen.webkitLockOrientation?
h=screen.webkitLockOrientation(e):screen.mozLockOrientation?h=screen.mozLockOrientation(e):screen.msLockOrientation&&(h=screen.msLockOrientation(e));h||console.warn("[Construct 3] Failed to lock orientation")}catch(h){console.warn("[Construct 3] Failed to lock orientation: ",h)}}Wa(){const e=f.Ua();e&&"any"!==this.$c&&this.ng();t(this,"fullscreenchange",{isFullscreen:e,innerWidth:this.xa(),innerHeight:this.wa()})}Ac(e){console.warn("[Construct 3] Fullscreen request failed: ",e);t(this,"fullscreenerror",
{isFullscreen:f.Ua(),innerWidth:this.xa(),innerHeight:this.wa()})}Ec(e){e?this.A.qc():this.A.Gc();t(this,"visibilitychange",{hidden:e})}zd(e,h){"Backspace"===h.key&&y(h);const c=b.get(h.code)||h.code;D(this,e,{code:c,key:h.key,which:h.which,repeat:h.repeat,altKey:h.altKey,ctrlKey:h.ctrlKey,metaKey:h.metaKey,shiftKey:h.shiftKey,timeStamp:h.timeStamp},d)}Cf(e){t(this,"wheel",{clientX:e.clientX,clientY:e.clientY,pageX:e.pageX,pageY:e.pageY,deltaX:e.deltaX,deltaY:e.deltaY,deltaZ:e.deltaZ,deltaMode:e.deltaMode,
timeStamp:e.timeStamp},d)}Bc(e,h,c){a(h)||D(this,e,{button:h.button,buttons:h.buttons,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,timeStamp:h.timeStamp},c)}Cc(e,h){if(!a(h)){var c=this.mb;"pointerdown"===e&&0!==c?e="pointermove":"pointerup"===e&&0!==h.buttons&&(e="pointermove");D(this,e,{pointerId:1,pointerType:"mouse",button:h.button,buttons:h.buttons,lastButtons:c,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:0,height:0,pressure:0,tangentialPressure:0,
tiltX:0,tiltY:0,twist:0,timeStamp:h.timeStamp},d);this.mb=h.buttons;this.Bc(h.type,h,g)}}Xa(e,h){if(this.pb&&"pointermove"!==e){var c=this.pb;c.fb||(L(c),c.Qb=Date.now())}c=0;"mouse"===h.pointerType&&(c=this.mb);D(this,e,{pointerId:h.pointerId,pointerType:h.pointerType,button:h.button,buttons:h.buttons,lastButtons:c,clientX:h.clientX,clientY:h.clientY,pageX:h.pageX,pageY:h.pageY,width:h.width||0,height:h.height||0,pressure:h.pressure||0,tangentialPressure:h.tangentialPressure||0,tiltX:h.tiltX||0,
tiltY:h.tiltY||0,twist:h.twist||0,timeStamp:h.timeStamp},d);"mouse"===h.pointerType&&(c="mousemove","pointerdown"===e?c="mousedown":"pointerup"===e&&(c="mouseup"),this.Bc(c,h,g),this.mb=h.buttons)}Df(e){this.Uc=e;e=this.pb;if(-1===e.Pa){var h=Date.now(),c=h-e.Qb,k=e.tg;c>=k&&e.Jd?(e.Qb=h,e.fb=!0,e.Kc(),e.fb=!1):e.Pa=self.setTimeout(e.be,Math.max(k-c,4))}}bf(){this.Xa("pointermove",this.Uc);this.Uc=null}Eb(e,h){for(let c=0,k=h.changedTouches.length;c<k;++c){const l=h.changedTouches[c];D(this,e,{pointerId:l.identifier,
pointerType:"touch",button:0,buttons:0,lastButtons:0,clientX:l.clientX,clientY:l.clientY,pageX:l.pageX,pageY:l.pageY,width:2*(l.radiusX||l.webkitRadiusX||0),height:2*(l.radiusY||l.webkitRadiusY||0),pressure:l.force||l.webkitForce||0,tangentialPressure:0,tiltX:0,tiltY:0,twist:l.rotationAngle||0,timeStamp:h.timeStamp},d)}}uc(e){window!==window.top&&window.focus();this.xd(e.target)&&document.activeElement&&!this.xd(document.activeElement)&&document.activeElement.blur()}xd(e){return!e||e===document||
e===window||e===document.body||"canvas"===e.tagName.toLowerCase()}Te(){this.Gd||(this.Gd=!0,window.addEventListener("deviceorientation",e=>this.sf(e)),window.addEventListener("deviceorientationabsolute",e=>this.tf(e)))}Se(){this.Fd||(this.Fd=!0,window.addEventListener("devicemotion",e=>this.rf(e)))}sf(e){t(this,"deviceorientation",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp,webkitCompassHeading:e.webkitCompassHeading,webkitCompassAccuracy:e.webkitCompassAccuracy},
d)}tf(e){t(this,"deviceorientationabsolute",{absolute:!!e.absolute,alpha:e.alpha||0,beta:e.beta||0,gamma:e.gamma||0,timeStamp:e.timeStamp},d)}rf(e){let h=null;var c=e.acceleration;c&&(h={x:c.x||0,y:c.y||0,z:c.z||0});c=null;var k=e.accelerationIncludingGravity;k&&(c={x:k.x||0,y:k.y||0,z:k.z||0});k=null;const l=e.rotationRate;l&&(k={alpha:l.alpha||0,beta:l.beta||0,gamma:l.gamma||0});t(this,"devicemotion",{acceleration:h,accelerationIncludingGravity:c,rotationRate:k,interval:e.interval,timeStamp:e.timeStamp},
d)}Lf(e){const h=this.A.K;h.style.width=e.styleWidth+"px";h.style.height=e.styleHeight+"px";h.style.marginLeft=e.marginLeft+"px";h.style.marginTop=e.marginTop+"px";this.Od&&(h.style.display="",this.Od=!1)}yf(e){const h=e.url;e=e.filename;const c=document.createElement("a"),k=document.body;c.textContent=e;c.href=h;c.download=e;k.appendChild(c);c.click();k.removeChild(c)}async Ff(e){var h=e.imageBitmapOpts;e=await self.C3_RasterSvgImageBlob(e.blob,e.imageWidth,e.imageHeight,e.surfaceWidth,e.surfaceHeight);
h=h?await createImageBitmap(e,h):await createImageBitmap(e);return{imageBitmap:h,transferables:[h]}}async wf(e){return await self.C3_GetSvgImageSize(e.blob)}async lf(e){await p(e.url)}Fc(){var e=[...this.Ja];this.Ja.clear();if(!this.oa)for(const h of e)(e=h.play())&&e.catch(()=>{this.Tb.has(h)||this.Ja.add(h)})}va(e){if("function"!==typeof e.play)throw Error("missing play function");this.Tb.delete(e);let h;try{h=e.play()}catch(c){this.Ja.add(e);return}h&&h.catch(()=>{this.Tb.has(e)||this.Ja.add(e)})}Ea(e){this.Ja.delete(e);
this.Tb.add(e)}Ab(e){this.oa=!!e}xf(){navigator.splashscreen&&navigator.splashscreen.hide&&navigator.splashscreen.hide()}qf(e){if(e.show){this.za||(this.za=document.createElement("div"),this.za.id="inspectOutline",document.body.appendChild(this.za));var h=this.za;h.style.display="";h.style.left=e.left-1+"px";h.style.top=e.top-1+"px";h.style.width=e.width+2+"px";h.style.height=e.height+2+"px";h.textContent=e.name}else this.za&&(this.za.style.display="none")}Gf(){window.C3_RegisterSW&&window.C3_RegisterSW()}Ad(e){window.c3_postToMessagePort&&
(e.from="runtime",window.c3_postToMessagePort(e))}jf(e,h){return this.A.nd(this.$a,"js-invoke-function",{name:e,params:h},void 0,void 0)}yc(e){alert(e.message)}Nf(e){"entered-fullscreen"===e?(f.Hb(!0),this.Wa()):"exited-fullscreen"===e?(f.Hb(!1),this.Wa()):console.warn("Unknown wrapper message: ",e)}})}"use strict";
async function N(f){if(f.sg)throw Error("already initialised");f.sg=!0;var a=f.Xb.tc("dispatchworker.js");f.Mc=await f.Xb.cc(a,f.F,{name:"DispatchWorker"});a=new MessageChannel;f.Qc=a.port1;f.Mc.postMessage({type:"_init","in-port":a.port2},[a.port2]);f.Yc=await P(f)}function O(f){return[f.Qc,f.Yc]}
async function P(f){const a=f.Qd.length;var b=f.Xb.tc("jobworker.js");b=await f.Xb.cc(b,f.F,{name:"JobWorker"+a});const d=new MessageChannel,g=new MessageChannel;f.Mc.postMessage({type:"_addJobWorker",port:d.port1},[d.port1]);b.postMessage({type:"init",number:a,"dispatch-port":d.port2,"output-port":g.port2},[d.port2,g.port2]);f.Qd.push(b);return g.port1}
self.Ee=class{constructor(f){this.Xb=f;this.F=f.F;this.F="preview"===f.u?this.F+"c3/workers/":this.F+f.Yb;this.vg=Math.min(navigator.hardwareConcurrency||2,16);this.Mc=null;this.Qd=[];this.Yc=this.Qc=null}};"use strict";window.C3_IsSupported&&(window.c3_runtimeInterface=new self.ma({Ig:!0,Jg:"workermain.js",Qa:["scripts/c3runtime.js"],ee:[],de:"",Fg:"scripts/",cd:[],ce:"html5"}));"use strict";
async function Q(f){var a=R(f.index);if(a&&(a=a.vibrationActuator)&&a.playEffect)try{await a.playEffect("dual-rumble",{duration:f.duration,startDelay:0,weakMagnitude:f.weakMag,strongMagnitude:f.strongMag})}catch(b){console.warn("[Gamepad] Failed to vibrate gamepad: ",b)}}function S(){return Array.from(navigator.getGamepads()).filter(f=>f&&f.connected)}function R(f){for(const a of S())if(a.index===f)return a;return null}
self.ma.Ra(class extends self.Ca{constructor(f){super(f,"gamepad");this.Pd=!!navigator.getGamepads;this.Sc=!1;F(this,"is-supported",()=>this.Pd);F(this,"ready",()=>{this.Sc=!0;for(const a of S())t(this,"gamepad-connected",{index:a.index,id:a.id});this.Pd&&I(this)});F(this,"vibrate",a=>Q(a));F(this,"reset-vibrate",a=>{(a=R(a.index))&&(a=a.vibrationActuator)&&a.reset&&a.reset()});window.addEventListener("gamepadconnected",a=>{this.Sc&&(a=a.gamepad,t(this,"gamepad-connected",{index:a.index,id:a.id}))});
window.addEventListener("gamepaddisconnected",a=>{this.Sc&&t(this,"gamepad-disconnected",{index:a.gamepad.index})});window.addEventListener("unload",()=>{for(const a of S()){const b=a.vibrationActuator;b&&b.reset&&b.reset()}})}ua(){var f=S();f.length&&(f=f.map(a=>({index:a.index,id:a.id,buttons:a.buttons.map(b=>({pressed:b.pressed,value:b.value})),axes:a.axes})),t(this,"input-update",f))}});"use strict";
{const f=180/Math.PI;self.da=class extends self.Ca{constructor(a){super(a,"audio");this.Mb=this.f=null;this.Ob=this.Pc=!1;this.qa=()=>this.og();this.aa=[];this.D=[];this.ga=null;this.Rd="";this.Sd=-1;this.ob=new Map;this.Vc=1;this.oa=!1;this.ad=0;this.$b=1;this.Nc=0;this.Ud="HRTF";this.Kd="inverse";this.Vd=600;this.Td=1E4;this.Xd=1;this.Md=this.Zc=!1;this.$d=this.A.De();this.ba=new Map;this.Ga=new Set;this.Rc=!1;this.Wc="";this.Aa=null;self.C3Audio_OnMicrophoneStream=(b,d)=>this.Bf(b,d);this.Lb=null;
self.C3Audio_GetOutputStream=()=>this.vf();self.C3Audio_DOMInterface=this;H(this,[["create-audio-context",b=>this.Ye(b)],["play",b=>this.Pf(b)],["stop",b=>this.lg(b)],["stop-all",()=>this.mg()],["set-paused",b=>this.eg(b)],["set-volume",b=>this.jg(b)],["fade-volume",b=>this.cf(b)],["set-master-volume",b=>this.cg(b)],["set-muted",b=>this.dg(b)],["set-silent",b=>this.gg(b)],["set-looping",b=>this.bg(b)],["set-playback-rate",b=>this.fg(b)],["seek",b=>this.Wf(b)],["preload",b=>this.Qf(b)],["unload",b=>
this.pg(b)],["unload-all",()=>this.qg()],["set-suspended",b=>this.hg(b)],["add-effect",b=>this.sd(b)],["set-effect-param",b=>this.Zf(b)],["remove-effects",b=>this.Sf(b)],["tick",b=>this.Kf(b)],["load-state",b=>this.zf(b)]])}async Ye(a){a.isiOSCordova&&(this.Zc=!0);this.ad=a.timeScaleMode;this.Ud=["equalpower","HRTF","soundfield"][a.panningModel];this.Kd=["linear","inverse","exponential"][a.distanceModel];this.Vd=a.refDistance;this.Td=a.maxDistance;this.Xd=a.rolloffFactor;var b={latencyHint:a.latencyHint};
this.$d||(b.sampleRate=48E3);if("undefined"!==typeof AudioContext)this.f=new AudioContext(b);else if("undefined"!==typeof webkitAudioContext)this.f=new webkitAudioContext(b);else throw Error("Web Audio API not supported");this.td();this.f.onstatechange=()=>{"running"!==this.f.state&&this.td()};this.Mb=this.f.createGain();this.Mb.connect(this.f.destination);b=a.listenerPos;this.f.listener.setPosition(b[0],b[1],b[2]);this.f.listener.setOrientation(0,0,1,0,-1,0);self.C3_GetAudioContextCurrentTime=()=>
this.dc();try{await Promise.all(a.preloadList.map(d=>this.Cb(d.originalUrl,d.url,d.type,!1)))}catch(d){console.error("[Construct 3] Preloading sounds failed: ",d)}return{sampleRate:this.f.sampleRate}}td(){this.Ob||(this.Pc=!1,window.addEventListener("pointerup",this.qa,!0),window.addEventListener("touchend",this.qa,!0),window.addEventListener("click",this.qa,!0),window.addEventListener("keydown",this.qa,!0),this.Ob=!0)}$e(){this.Ob&&(this.Pc=!0,window.removeEventListener("pointerup",this.qa,!0),window.removeEventListener("touchend",
this.qa,!0),window.removeEventListener("click",this.qa,!0),window.removeEventListener("keydown",this.qa,!0),this.Ob=!1)}og(){if(!this.Pc){var a=this.f;"suspended"===a.state&&a.resume&&a.resume();var b=a.createBuffer(1,220,22050),d=a.createBufferSource();d.buffer=b;d.connect(a.destination);d.start(0);"running"===a.state&&this.$e()}}W(){return this.f}dc(){return this.f.currentTime}sa(){return this.Mb}jd(a){return(a=this.ba.get(a.toLowerCase()))?a[0].P():this.sa()}fe(a,b){a=a.toLowerCase();let d=this.ba.get(a);
d||(d=[],this.ba.set(a,d));b.ag(d.length);b.ig(a);d.push(b);this.Dd(a)}Dd(a){let b=this.sa();const d=this.ba.get(a);if(d&&d.length){b=d[0].P();for(let g=0,m=d.length;g<m;++g){const p=d[g];g+1===m?p.S(this.sa()):p.S(d[g+1].P())}}for(const g of this.la(a))g.Je(b);this.Aa&&this.Wc===a&&(this.Aa.disconnect(),this.Aa.connect(b))}wb(){return this.Vc}xb(){return this.oa}$f(){this.Md=!0}xe(a,b){return b?this.A.rg(a).then(d=>{const g=this.f.createBuffer(1,d.length,48E3);g.getChannelData(0).set(d);return g}):
new Promise((d,g)=>{this.f.decodeAudioData(a,d,g)})}va(a){this.A.va(a)}Ea(a){this.A.Ea(a)}od(a){let b=0;for(let d=0,g=this.D.length;d<g;++d){const m=this.D[d];this.D[b]=m;m.L===a?m.c():++b}this.D.length=b}Ke(){let a=0;for(let b=0,d=this.aa.length;b<d;++b){const g=this.aa[b];this.aa[a]=g;g.ta()?g.c():++a}this.aa.length=a}*la(a){if(a)for(const b of this.D)self.da.ye(b.Z,a)&&(yield b);else this.ga&&!this.ga.T()&&(yield this.ga)}async Cb(a,b,d,g,m){for(const p of this.aa)if(p.Ta()===b)return await T(p),
p;if(m)return null;g&&(this.Zc||this.Md)&&this.Ke();m="audio/webm; codecs=opus"===d&&!this.$d;g&&m&&this.$f();a=!g||this.Zc||m?new self.te(this,a,b,d,g,m):new self.re(this,a,b,d,g);this.aa.push(a);await T(a);return a}async sc(a,b,d,g,m){for(const p of this.D)if(p.Ta()===b&&(p.bc()||m))return p.Me(g),p;a=await this.Cb(a,b,d,m);g="html5"===a.Ic?new self.se(a.i,a,g):new self.ue(a.i,a,g);this.D.push(g);return g}Qe(a){let b=this.ob.get(a);if(!b){let d=null;b={bd:0,promise:new Promise(g=>d=g),resolve:d};
this.ob.set(a,b)}b.bd++}Tf(a){const b=this.ob.get(a);if(!b)throw Error("expected pending tag");b.bd--;0===b.bd&&(b.resolve(),this.ob.delete(a))}pc(a){a||(a=this.Rd);return(a=this.ob.get(a))?a.promise:Promise.resolve()}Db(){if(0<this.Ga.size)I(this);else for(const a of this.D)if(a.kd()){I(this);break}}ua(){for(var a of this.Ga)a.ua();a=this.dc();for(var b of this.D)b.ua(a);b=this.D.filter(d=>d.kd()).map(d=>d.Sa());t(this,"state",{tickCount:this.Sd,audioInstances:b,analysers:[...this.Ga].map(d=>d.Ae())});
0===b.length&&0===this.Ga.size&&this.Pb&&(this.A.Uf(this.ae),this.Pb=!1)}lc(a,b,d){t(this,"trigger",{type:a,tag:b,aiid:d})}async Pf(a){const b=a.originalUrl,d=a.url,g=a.type,m=a.isMusic,p=a.tag,x=a.isLooping,A=a.vol,B=a.pos,v=a.panning;let w=a.off;0<w&&!a.trueClock&&(this.f.getOutputTimestamp?(a=this.f.getOutputTimestamp(),w=w-a.performanceTime/1E3+a.contextTime):w=w-performance.now()/1E3+this.f.currentTime);this.Rd=p;this.Qe(p);try{this.ga=await this.sc(b,d,g,p,m),v?(this.ga.zb(!0),this.ga.Le(v.x,
v.y,v.angle,v.innerAngle,v.outerAngle,v.outerGain),v.hasOwnProperty("uid")&&this.ga.Ne(v.uid)):this.ga.zb(!1),this.ga.Play(x,A,B,w)}catch(C){console.error("[Construct 3] Audio: error starting playback: ",C);return}finally{this.Tf(p)}I(this)}lg(a){a=a.tag;for(const b of this.la(a))b.na()}mg(){for(const a of this.D)a.na()}eg(a){const b=a.tag;a=a.paused;for(const d of this.la(b))a?d.Va():d.yb();this.Db()}jg(a){const b=a.tag;a=a.vol;for(const d of this.la(b))d.Bb(a)}async cf(a){const b=a.tag,d=a.vol,
g=a.duration;a=a.stopOnEnd;await this.pc(b);for(const m of this.la(b))m.ze(d,g,a);this.Db()}cg(a){this.Vc=a.vol;for(const b of this.D)b.Jb()}dg(a){const b=a.tag;a=a.isMuted;for(const d of this.la(b))d.pd(a)}gg(a){this.oa=a.isSilent;this.A.Ab(this.oa);for(const b of this.D)b.Ib()}bg(a){const b=a.tag;a=a.isLooping;for(const d of this.la(b))d.nc(a)}async fg(a){const b=a.tag;a=a.rate;await this.pc(b);for(const d of this.la(b))d.rd(a)}async Wf(a){const b=a.tag;a=a.pos;await this.pc(b);for(const d of this.la(b))d.mc(a)}async Qf(a){const b=
a.originalUrl,d=a.url,g=a.type;a=a.isMusic;try{await this.sc(b,d,g,"",a)}catch(m){console.error("[Construct 3] Audio: error preloading: ",m)}}async pg(a){if(a=await this.Cb("",a.url,a.type,a.isMusic,!0))a.c(),a=this.aa.indexOf(a),-1!==a&&this.aa.splice(a,1)}qg(){for(const a of this.aa)a.c();this.aa.length=0}hg(a){a=a.isSuspended;!a&&this.f.resume&&this.f.resume();for(const b of this.D)b.oc(a);a&&this.f.suspend&&this.f.suspend()}Kf(a){this.$b=a.timeScale;this.Nc=a.gameTime;this.Sd=a.tickCount;if(0!==
this.ad)for(var b of this.D)b.Fa();(b=a.listenerPos)&&this.f.listener.setPosition(b[0],b[1],b[2]);for(const d of a.instPans){a=d.uid;for(const g of this.D)g.fa===a&&g.qd(d.x,d.y,d.angle)}}async sd(a){var b=a.type;const d=a.tag;var g=a.params;if("filter"===b)g=new self.le(this,...g);else if("delay"===b)g=new self.je(this,...g);else if("convolution"===b){b=null;try{b=await this.Cb(a.bufferOriginalUrl,a.bufferUrl,a.bufferType,!1)}catch(m){console.log("[Construct 3] Audio: error loading convolution: ",
m);return}g=new self.ie(this,b.$,...g);g.Xf(a.bufferOriginalUrl,a.bufferType)}else if("flanger"===b)g=new self.me(this,...g);else if("phaser"===b)g=new self.oe(this,...g);else if("gain"===b)g=new self.ne(this,...g);else if("tremolo"===b)g=new self.qe(this,...g);else if("ringmod"===b)g=new self.pe(this,...g);else if("distortion"===b)g=new self.ke(this,...g);else if("compressor"===b)g=new self.he(this,...g);else if("analyser"===b)g=new self.ge(this,...g);else throw Error("invalid effect type");this.fe(d,
g);this.Cd()}Zf(a){const b=a.index,d=a.param,g=a.value,m=a.ramp,p=a.time;a=this.ba.get(a.tag);!a||0>b||b>=a.length||(a[b].X(d,g,m,p),this.Cd())}Sf(a){a=a.tag.toLowerCase();const b=this.ba.get(a);if(b&&b.length){for(const d of b)d.c();this.ba.delete(a);this.Dd(a)}}Pe(a){this.Ga.add(a);this.Db()}Rf(a){this.Ga.delete(a)}Cd(){this.Rc||(this.Rc=!0,Promise.resolve().then(()=>this.af()))}af(){const a={};for(const [b,d]of this.ba)a[b]=d.map(g=>g.Sa());t(this,"fxstate",{fxstate:a});this.Rc=!1}async zf(a){const b=
a.saveLoadMode;if(3!==b)for(var d of this.D)d.ta()&&1===b||(d.ta()||2!==b)&&d.na();for(const g of this.ba.values())for(const m of g)m.c();this.ba.clear();this.$b=a.timeScale;this.Nc=a.gameTime;d=a.listenerPos;this.f.listener.setPosition(d[0],d[1],d[2]);this.oa=a.isSilent;this.A.Ab(this.oa);this.Vc=a.masterVolume;d=[];for(const g of Object.values(a.effects))d.push(Promise.all(g.map(m=>this.sd(m))));await Promise.all(d);await Promise.all(a.playing.map(g=>this.kf(g,b)));this.Db()}async kf(a,b){if(3!==
b){var d=a.bufferOriginalUrl,g=a.bufferUrl,m=a.bufferType,p=a.isMusic,x=a.tag,A=a.isLooping,B=a.volume,v=a.playbackTime;if(!p||1!==b)if(p||2!==b){b=null;try{b=await this.sc(d,g,m,x,p)}catch(w){console.error("[Construct 3] Audio: error loading audio state: ",w);return}b.He(a.pan);b.Play(A,B,v,0);a.isPlaying||b.Va();b.wc(a)}}}Bf(a,b){this.Aa&&this.Aa.disconnect();this.Wc=b.toLowerCase();this.Aa=this.f.createMediaStreamSource(a);this.Aa.connect(this.jd(this.Wc))}vf(){this.Lb||(this.Lb=this.f.createMediaStreamDestination(),
this.Mb.connect(this.Lb));return this.Lb.stream}static ye(a,b){return a.length!==b.length?!1:a===b?!0:a.toLowerCase()===b.toLowerCase()}static Oe(a){return a*f}static we(a){return Math.pow(10,a/20)}static hd(a){return Math.max(Math.min(self.da.we(a),1),0)}static Ge(a){return Math.log(a)/Math.log(10)*20}static Fe(a){return self.da.Ge(Math.max(Math.min(a,1),0))}static Bg(a,b){return 1-Math.exp(-b*a)}};self.ma.Ra(self.da)}"use strict";function T(f){f.Rb||(f.Rb=f.vc());return f.Rb}
self.ed=class{constructor(f,a,b,d,g){this.i=f;this.xg=a;this.Ba=b;this.R=d;this.ug=g;this.Ic="";this.Rb=null}c(){this.Rb=this.i=null}vc(){}W(){return this.i.W()}fc(){return this.xg}Ta(){return this.Ba}ec(){return this.R}ta(){return this.ug}ea(){}};"use strict";
self.re=class extends self.ed{constructor(f,a,b,d,g){super(f,a,b,d,g);this.Ic="html5";this.J=new Audio;this.J.crossOrigin="anonymous";this.J.autoplay=!1;this.J.preload="auto";this.ib=this.jb=null;this.J.addEventListener("canplaythrough",()=>!0);this.nb=this.W().createGain();this.lb=null;this.J.addEventListener("canplay",()=>{this.jb&&(this.jb(),this.ib=this.jb=null);!this.lb&&this.J&&(this.lb=this.W().createMediaElementSource(this.J),this.lb.connect(this.nb))});this.onended=null;this.J.addEventListener("ended",
()=>{if(this.onended)this.onended()});this.J.addEventListener("error",m=>{console.error(`[Construct 3] Audio '${this.Ba}' error: `,m);this.ib&&(this.ib(m),this.ib=this.jb=null)})}c(){this.i.od(this);this.nb.disconnect();this.nb=null;this.lb.disconnect();this.lb=null;this.J&&!this.J.paused&&this.J.pause();this.J=this.onended=null;super.c()}vc(){return new Promise((f,a)=>{this.jb=f;this.ib=a;this.J.src=this.Ba})}O(){return this.J}ea(){return this.J.duration}};"use strict";
async function V(f){if(f.ya)return f.ya;var a=f.i.A;if("cordova"===a.u&&a.ld(f.Ba)&&"file:"===location.protocol)f.ya=await a.ub(f.Ba);else{a=await fetch(f.Ba);if(!a.ok)throw Error(`error fetching audio data: ${a.status} ${a.statusText}`);f.ya=await a.arrayBuffer()}}async function W(f){if(f.$)return f.$;f.$=await f.i.xe(f.ya,f.wg);f.ya=null}
self.te=class extends self.ed{constructor(f,a,b,d,g,m){super(f,a,b,d,g);this.Ic="webaudio";this.$=this.ya=null;this.wg=!!m}c(){this.i.od(this);this.$=this.ya=null;super.c()}async vc(){try{await V(this),await W(this)}catch(f){console.error(`[Construct 3] Failed to load audio '${this.Ba}': `,f)}}ea(){return this.$?this.$.duration:0}};"use strict";
{let f=0;self.fd=class{constructor(a,b,d){this.i=a;this.L=b;this.Z=d;this.Kb=f++;this.M=this.W().createGain();this.M.connect(this.sa());this.B=null;this.gb=!1;this.ja=[0,0,0];this.ia=[0,0,0];this.H=!0;this.V=this.ka=this.G=!1;this.rb=1;this.Ha=!1;this.Y=1;a=this.i.ad;this.Tc=1===a&&!this.ta()||2===a;this.cb=this.fa=-1;this.Zd=!1}c(){this.L=this.i=null;this.B&&(this.B.disconnect(),this.B=null);this.M.disconnect();this.M=null}W(){return this.i.W()}sa(){return this.i.jd(this.Z)}wb(){return this.i.wb()}vb(){return this.Tc?
this.i.Nc:performance.now()/1E3}fc(){return this.L.fc()}Ta(){return this.L.Ta()}ec(){return this.L.ec()}ta(){return this.L.ta()}Me(a){this.Z=a}T(){}bc(){}IsPlaying(){return!this.H&&!this.G&&!this.T()}kd(){return!this.H&&!this.T()}Da(){}ea(){return this.L.ea()}Play(){}na(){}Va(){}yb(){}Bb(a){this.rb=a;this.M.gain.cancelScheduledValues(0);this.cb=-1;this.M.gain.value=this.hc()}ze(a,b,d){if(!this.Ha){a*=this.wb();var g=this.M.gain;g.cancelScheduledValues(0);var m=this.i.dc();b=m+b;g.setValueAtTime(g.value,
m);g.linearRampToValueAtTime(a,b);this.rb=a;this.cb=b;this.Zd=d}}Jb(){this.Bb(this.rb)}ua(a){-1!==this.cb&&a>=this.cb&&(this.cb=-1,this.Zd&&this.na(),this.i.lc("fade-ended",this.Z,this.Kb))}hc(){const a=this.rb*this.wb();return isFinite(a)?a:0}pd(a){a=!!a;this.Ha!==a&&(this.Ha=a,this.Ib())}xb(){return this.i.xb()}Ib(){}nc(){}rd(a){this.Y!==a&&(this.Y=a,this.Fa())}Fa(){}mc(){}oc(){}zb(a){a=!!a;this.gb!==a&&((this.gb=a)?(this.B||(this.B=this.W().createPanner(),this.B.panningModel=this.i.Ud,this.B.distanceModel=
this.i.Kd,this.B.refDistance=this.i.Vd,this.B.maxDistance=this.i.Td,this.B.rolloffFactor=this.i.Xd),this.M.disconnect(),this.M.connect(this.B),this.B.connect(this.sa())):(this.B.disconnect(),this.M.disconnect(),this.M.connect(this.sa())))}Le(a,b,d,g,m,p){this.gb&&(this.qd(a,b,d),a=self.da.Oe,this.B.coneInnerAngle=a(g),this.B.coneOuterAngle=a(m),this.B.coneOuterGain=p)}qd(a,b,d){this.gb&&(this.ja[0]=a,this.ja[1]=b,this.ja[2]=0,this.ia[0]=Math.cos(d),this.ia[1]=Math.sin(d),this.ia[2]=0,this.B.setPosition(...this.ja),
this.B.setOrientation(...this.ia))}Ne(a){this.fa=a}ic(){}Je(a){const b=this.B||this.M;b.disconnect();b.connect(a)}Sa(){return{aiid:this.Kb,tag:this.Z,duration:this.ea(),volume:this.rb,isPlaying:this.IsPlaying(),playbackTime:this.Da(),playbackRate:this.Y,uid:this.fa,bufferOriginalUrl:this.fc(),bufferUrl:"",bufferType:this.ec(),isMusic:this.ta(),isLooping:this.V,isMuted:this.Ha,resumePosition:this.ic(),pan:this.Be()}}wc(a){this.rd(a.playbackRate);this.pd(a.isMuted)}Be(){if(!this.B)return null;const a=
this.B;return{pos:this.ja,orient:this.ia,cia:a.coneInnerAngle,coa:a.coneOuterAngle,cog:a.coneOuterGain,uid:this.fa}}He(a){if(a){this.zb(!0);a=this.B;var b=a.pos;this.ja[0]=b[0];this.ja[1]=b[1];this.ja[2]=b[2];b=a.orient;this.ia[0]=b[0];this.ia[1]=b[1];this.ia[2]=b[2];a.setPosition(...this.ja);a.setOrientation(...this.ia);a.coneInnerAngle=a.cia;a.coneOuterAngle=a.coa;a.coneOuterGain=a.cog;this.fa=a.uid}else this.zb(!1)}}}"use strict";
self.se=class extends self.fd{constructor(f,a,b){super(f,a,b);this.L.nb.connect(this.M);this.L.onended=()=>this.zc()}c(){this.na();this.L.nb.disconnect();super.c()}O(){return this.L.O()}zc(){this.H=!0;this.fa=-1;this.i.lc("ended",this.Z,this.Kb)}T(){return this.O().ended}bc(){return this.H?!0:this.T()}Da(f){let a=this.O().currentTime;f&&(a*=this.Y);this.V||(a=Math.min(a,this.ea()));return a}Play(f,a,b){const d=this.O();1!==d.playbackRate&&(d.playbackRate=1);d.loop!==f&&(d.loop=f);this.Bb(a);d.muted&&
(d.muted=!1);if(d.currentTime!==b)try{d.currentTime=b}catch(g){console.warn(`[Construct 3] Exception seeking audio '${this.L.Ta()}' to position '${b}': `,g)}this.i.va(d);this.G=this.H=!1;this.V=f;this.Y=1}na(){const f=this.O();f.paused||f.pause();this.i.Ea(f);this.H=!0;this.G=!1;this.fa=-1}Va(){if(!(this.G||this.H||this.T())){var f=this.O();f.paused||f.pause();this.i.Ea(f);this.G=!0}}yb(){!this.G||this.H||this.T()||(this.i.va(this.O()),this.G=!1)}Ib(){this.O().muted=this.Ha||this.xb()}nc(f){f=!!f;
this.V!==f&&(this.V=f,this.O().loop=f)}Fa(){let f=this.Y;this.Tc&&(f*=this.i.$b);try{this.O().playbackRate=f}catch(a){console.warn(`[Construct 3] Unable to set playback rate '${f}':`,a)}}mc(f){if(!this.H&&!this.T())try{this.O().currentTime=f}catch(a){console.warn(`[Construct 3] Error seeking audio to '${f}': `,a)}}ic(){return this.Da()}oc(f){f?this.IsPlaying()?(this.O().pause(),this.ka=!0):this.ka=!1:this.ka&&(this.i.va(this.O()),this.ka=!1)}};"use strict";
function X(f){f.j&&f.j.disconnect();f.j=null;f.Za=null}
self.ue=class extends self.fd{constructor(f,a,b){super(f,a,b);this.j=null;this.Ub=d=>this.zc(d);this.Oc=!0;this.Za=null;this.N=this.Zb=0;this.Xc=1}c(){this.na();X(this);this.Ub=null;super.c()}zc(f){this.G||this.ka||f.target!==this.Za||(this.H=this.Oc=!0,this.fa=-1,X(this),this.i.lc("ended",this.Z,this.Kb))}T(){return!this.H&&this.j&&this.j.loop||this.G?!1:this.Oc}bc(){return!this.j||this.H?!0:this.T()}Da(f){let a;a=this.G?this.N:this.vb()-this.Zb;f&&(a*=this.Y);this.V||(a=Math.min(a,this.ea()));return a}Play(f,
a,b,d){this.Xc=1;this.Bb(a);X(this);this.j=this.W().createBufferSource();this.j.buffer=this.L.$;this.j.connect(this.M);this.Za=this.j;this.j.onended=this.Ub;this.j.loop=f;this.j.start(d,b);this.G=this.H=this.Oc=!1;this.V=f;this.Y=1;this.Zb=this.vb()-b}na(){if(this.j)try{this.j.stop(0)}catch(f){}this.H=!0;this.G=!1;this.fa=-1}Va(){this.G||this.H||this.T()||(this.N=this.Da(!0),this.V&&(this.N%=this.ea()),this.G=!0,this.j.stop(0))}yb(){!this.G||this.H||this.T()||(X(this),this.j=this.W().createBufferSource(),
this.j.buffer=this.L.$,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Jb(),this.Fa(),this.Zb=this.vb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.G=!1)}hc(){return super.hc()*this.Xc}Ib(){this.Xc=this.Ha||this.xb()?0:1;this.Jb()}nc(f){f=!!f;this.V!==f&&(this.V=f,this.j&&(this.j.loop=f))}Fa(){let f=this.Y;this.Tc&&(f*=this.i.$b);this.j&&(this.j.playbackRate.value=f)}mc(f){this.H||this.T()||(this.G?this.N=f:(this.Va(),this.N=f,this.yb()))}ic(){return this.N}oc(f){f?
this.IsPlaying()?(this.ka=!0,this.N=this.Da(!0),this.V&&(this.N%=this.ea()),this.j.stop(0)):this.ka=!1:this.ka&&(X(this),this.j=this.W().createBufferSource(),this.j.buffer=this.L.$,this.j.connect(this.M),this.Za=this.j,this.j.onended=this.Ub,this.j.loop=this.V,this.Jb(),this.Fa(),this.Zb=this.vb()-this.N/(this.Y||.001),this.j.start(0,this.N),this.ka=!1)}wc(f){super.wc(f);this.N=f.resumePosition}};"use strict";
{class f{constructor(a){this.i=a;this.f=a.W();this.Nd=-1;this.R=this.Z="";this.g=null}c(){this.f=null}ag(a){this.Nd=a}ig(a){this.Z=a}o(){return this.f.createGain()}P(){}S(){}m(a,b,d,g){a.cancelScheduledValues(0);if(0===g)a.value=b;else{var m=this.f.currentTime;g+=m;switch(d){case 0:a.setValueAtTime(b,g);break;case 1:a.setValueAtTime(a.value,m);a.linearRampToValueAtTime(b,g);break;case 2:a.setValueAtTime(a.value,m),a.exponentialRampToValueAtTime(b,g)}}}Sa(){return{type:this.R,tag:this.Z,params:this.g}}}
self.le=class extends f{constructor(a,b,d,g,m,p,x){super(a);this.R="filter";this.g=[b,d,g,m,p,x];this.l=this.o();this.b=this.o();this.b.gain.value=x;this.a=this.o();this.a.gain.value=1-x;this.v=this.f.createBiquadFilter();this.v.type=b;this.v.frequency.value=d;this.v.detune.value=g;this.v.Q.value=m;this.v.gain.vlaue=p;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b)}c(){this.l.disconnect();this.v.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();
this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 1:this.g[1]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[2]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[3]=b;this.m(this.v.Q,b,d,g);break;case 4:this.g[4]=b,this.m(this.v.gain,b,d,g)}}};self.je=class extends f{constructor(a,b,d,g){super(a);this.R="delay";this.g=[b,d,g];this.l=
this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=1-g;this.kb=this.o();this.U=this.f.createDelay(b);this.U.delayTime.value=b;this.bb=this.o();this.bb.gain.value=d;this.l.connect(this.kb);this.l.connect(this.a);this.kb.connect(this.b);this.kb.connect(this.U);this.U.connect(this.bb);this.bb.connect(this.kb)}c(){this.l.disconnect();this.b.disconnect();this.a.disconnect();this.kb.disconnect();this.U.disconnect();this.bb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);
this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){const m=self.da.hd;switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[2]=b;this.m(this.b.gain,b,d,g);this.m(this.a.gain,1-b,d,g);break;case 4:this.g[1]=m(b);this.m(this.bb.gain,m(b),d,g);break;case 5:this.g[0]=b,this.m(this.U.delayTime,b,d,g)}}};self.ie=class extends f{constructor(a,b,d,g){super(a);this.R="convolution";this.g=[d,g];this.Id=this.Hd="";this.l=this.o();this.b=this.o();this.b.gain.value=g;this.a=this.o();this.a.gain.value=
1-g;this.ab=this.f.createConvolver();this.ab.normalize=d;this.ab.buffer=b;this.l.connect(this.ab);this.l.connect(this.a);this.ab.connect(this.b)}c(){this.l.disconnect();this.ab.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[1]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}Xf(a,b){this.Hd=a;this.Id=b}Sa(){const a=
super.Sa();a.bufferOriginalUrl=this.Hd;a.bufferUrl="";a.bufferType=this.Id;return a}};self.me=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="flanger";this.g=[b,d,g,m,p];this.l=this.o();this.a=this.o();this.a.gain.value=1-p/2;this.b=this.o();this.b.gain.value=p/2;this.eb=this.o();this.eb.gain.value=m;this.U=this.f.createDelay(b+d);this.U.delayTime.value=b;this.s=this.f.createOscillator();this.s.frequency.value=g;this.I=this.o();this.I.gain.value=d;this.l.connect(this.U);this.l.connect(this.a);
this.U.connect(this.b);this.U.connect(this.eb);this.eb.connect(this.U);this.s.connect(this.I);this.I.connect(this.U.delayTime);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.U.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();this.eb.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[4]=b;this.m(this.b.gain,
b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 6:this.g[1]=b/1E3;this.m(this.I.gain,b/1E3,d,g);break;case 7:this.g[2]=b;this.m(this.s.frequency,b,d,g);break;case 8:this.g[3]=b/100,this.m(this.eb.gain,b/100,d,g)}}};self.oe=class extends f{constructor(a,b,d,g,m,p,x){super(a);this.R="phaser";this.g=[b,d,g,m,p,x];this.l=this.o();this.a=this.o();this.a.gain.value=1-x/2;this.b=this.o();this.b.gain.value=x/2;this.v=this.f.createBiquadFilter();this.v.type="allpass";this.v.frequency.value=b;this.v.detune.value=
d;this.v.Q.value=g;this.s=this.f.createOscillator();this.s.frequency.value=p;this.I=this.o();this.I.gain.value=m;this.l.connect(this.v);this.l.connect(this.a);this.v.connect(this.b);this.s.connect(this.I);this.I.connect(this.v.frequency);this.s.start(0)}c(){this.s.stop(0);this.l.disconnect();this.v.disconnect();this.s.disconnect();this.I.disconnect();this.a.disconnect();this.b.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,
b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[5]=b;this.m(this.b.gain,b/2,d,g);this.m(this.a.gain,1-b/2,d,g);break;case 1:this.g[0]=b;this.m(this.v.frequency,b,d,g);break;case 2:this.g[1]=b;this.m(this.v.detune,b,d,g);break;case 3:this.g[2]=b;this.m(this.v.Q,b,d,g);break;case 6:this.g[3]=b;this.m(this.I.gain,b,d,g);break;case 7:this.g[4]=b,this.m(this.s.frequency,b,d,g)}}};self.ne=class extends f{constructor(a,b){super(a);this.R="gain";this.g=[b];this.h=this.o();this.h.gain.value=
b}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){const m=self.da.hd;switch(a){case 4:this.g[0]=m(b),this.m(this.h.gain,m(b),d,g)}}};self.qe=class extends f{constructor(a,b,d){super(a);this.R="tremolo";this.g=[b,d];this.h=this.o();this.h.gain.value=1-d/2;this.s=this.f.createOscillator();this.s.frequency.value=b;this.I=this.o();this.I.gain.value=d/2;this.s.connect(this.I);this.I.connect(this.h.gain);this.s.start(0)}c(){this.s.stop(0);this.s.disconnect();
this.I.disconnect();this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.h.gain,1-b/2,d,g);this.m(this.I.gain,b/2,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.pe=class extends f{constructor(a,b,d){super(a);this.R="ringmod";this.g=[b,d];this.l=this.o();this.b=this.o();this.b.gain.value=d;this.a=this.o();this.a.gain.value=1-d;this.qb=this.o();this.qb.gain.value=
0;this.s=this.f.createOscillator();this.s.frequency.value=b;this.s.connect(this.qb.gain);this.s.start(0);this.l.connect(this.qb);this.l.connect(this.a);this.qb.connect(this.b)}c(){this.s.stop(0);this.s.disconnect();this.qb.disconnect();this.l.disconnect();this.b.disconnect();this.a.disconnect();super.c()}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0);this.g[1]=b;this.m(this.b.gain,b,d,g);
this.m(this.a.gain,1-b,d,g);break;case 7:this.g[0]=b,this.m(this.s.frequency,b,d,g)}}};self.ke=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="distortion";this.g=[b,d,g,m,p];this.l=this.o();this.Wb=this.o();this.Vb=this.o();this.Yf(g,m);this.b=this.o();this.b.gain.value=p;this.a=this.o();this.a.gain.value=1-p;this.ac=this.f.createWaveShaper();this.Lc=new Float32Array(65536);this.ef(b,d);this.ac.curve=this.Lc;this.l.connect(this.Wb);this.l.connect(this.a);this.Wb.connect(this.ac);this.ac.connect(this.Vb);
this.Vb.connect(this.b)}c(){this.l.disconnect();this.Wb.disconnect();this.ac.disconnect();this.Vb.disconnect();this.b.disconnect();this.a.disconnect();super.c()}Yf(a,b){.01>a&&(a=.01);this.Wb.gain.value=a;this.Vb.gain.value=Math.pow(1/a,.6)*b}ef(a,b){for(let d=0;32768>d;++d){let g=d/32768;g=this.kg(g,a,b);this.Lc[32768+d]=g;this.Lc[32768-d-1]=-g}}kg(a,b,d){d=1.05*d*b-b;const g=0>a?-a:a;return(g<b?g:b+d*self.da.Bg(g-b,1/d))*(0>a?-1:1)}S(a){this.b.disconnect();this.b.connect(a);this.a.disconnect();
this.a.connect(a)}P(){return this.l}X(a,b,d,g){switch(a){case 0:b=Math.max(Math.min(b/100,1),0),this.g[4]=b,this.m(this.b.gain,b,d,g),this.m(this.a.gain,1-b,d,g)}}};self.he=class extends f{constructor(a,b,d,g,m,p){super(a);this.R="compressor";this.g=[b,d,g,m,p];this.h=this.f.createDynamicsCompressor();this.h.threshold.value=b;this.h.knee.value=d;this.h.ratio.value=g;this.h.attack.value=m;this.h.release.value=p}c(){this.h.disconnect();super.c()}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}};
self.ge=class extends f{constructor(a,b,d){super(a);this.R="analyser";this.g=[b,d];this.h=this.f.createAnalyser();this.h.fftSize=b;this.h.smoothingTimeConstant=d;this.Ld=new Float32Array(this.h.frequencyBinCount);this.Yd=new Uint8Array(b);this.Wd=this.Ka=0;this.i.Pe(this)}c(){this.i.Rf(this);this.h.disconnect();super.c()}ua(){this.h.getFloatFrequencyData(this.Ld);this.h.getByteTimeDomainData(this.Yd);const a=this.h.fftSize;let b=this.Ka=0;for(var d=0;d<a;++d){let g=(this.Yd[d]-128)/128;0>g&&(g=-g);
this.Ka<g&&(this.Ka=g);b+=g*g}d=self.da.Fe;this.Ka=d(this.Ka);this.Wd=d(Math.sqrt(b/a))}S(a){this.h.disconnect();this.h.connect(a)}P(){return this.h}X(){}Ae(){return{tag:this.Z,index:this.Nd,peak:this.Ka,rms:this.Wd,binCount:this.h.frequencyBinCount,freqBins:this.Ld}}}}"use strict";function Y(f){window.C3_RegisterSW&&window.OfflineClientInfo&&window.OfflineClientInfo.SetMessageCallback(a=>t(f,"sw-message",a.data))}
function Z(f){f=f.orientation;if(screen.orientation&&screen.orientation.lock)screen.orientation.lock(f).catch(a=>console.warn("[Construct 3] Failed to lock orientation: ",a));else try{let a=!1;screen.lockOrientation?a=screen.lockOrientation(f):screen.webkitLockOrientation?a=screen.webkitLockOrientation(f):screen.mozLockOrientation?a=screen.mozLockOrientation(f):screen.msLockOrientation&&(a=screen.msLockOrientation(f));a||console.warn("[Construct 3] Failed to lock orientation")}catch(a){console.warn("[Construct 3] Failed to lock orientation: ",
a)}}
self.ma.Ra(class extends self.Ca{constructor(f){super(f,"browser");this.u="";H(this,[["get-initial-state",a=>{this.u=a.exportType;return{location:location.toString(),isOnline:!!navigator.onLine,referrer:document.referrer,title:document.title,isCookieEnabled:!!navigator.cookieEnabled,screenWidth:screen.width,screenHeight:screen.height,windowOuterWidth:window.outerWidth,windowOuterHeight:window.outerHeight,isScirraArcade:"undefined"!==typeof window.is_scirra_arcade}}],["ready-for-sw-messages",()=>Y(this)],
["alert",a=>this.yc(a)],["close",()=>{navigator.app&&navigator.app.exitApp?navigator.app.exitApp():navigator.device&&navigator.device.exitApp?navigator.device.exitApp():window.close()}],["set-focus",a=>this.Dc(a)],["vibrate",a=>{navigator.vibrate&&navigator.vibrate(a.pattern)}],["lock-orientation",a=>Z(a)],["unlock-orientation",()=>{try{screen.orientation&&screen.orientation.unlock?screen.orientation.unlock():screen.unlockOrientation?screen.unlockOrientation():screen.webkitUnlockOrientation?screen.webkitUnlockOrientation():
screen.mozUnlockOrientation?screen.mozUnlockOrientation():screen.msUnlockOrientation&&screen.msUnlockOrientation()}catch(a){}}],["navigate",a=>{var b=a.type;if("back"===b)navigator.app&&navigator.app.backHistory?navigator.app.backHistory():window.history.back();else if("forward"===b)window.history.forward();else if("reload"===b)location.reload();else if("url"===b){b=a.url;var d=a.target;a=a.exportType;"windows-uwp"===a&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):
self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):"preview"===a||"windows-webview2"===a?window.open(b,"_blank"):this.Og||(2===d?window.top.location=b:1===d?window.parent.location=b:window.location=b)}else"new-window"===b&&(b=a.url,d=a.tag,"windows-uwp"===a.exportType&&"undefined"!==typeof Windows?Windows.System.Launcher.launchUriAsync(new Windows.Foundation.Uri(b)):self.cordova&&self.cordova.InAppBrowser?self.cordova.InAppBrowser.open(b,"_system"):window.open(b,d))}],
["request-fullscreen",a=>{if("windows-webview2"===this.u||"macos-wkwebview"===this.u)self.ma.Hb(!0),this.A.Hc({type:"set-fullscreen",fullscreen:!0});else{const b={navigationUI:"auto"};a=a.navUI;1===a?b.navigationUI="hide":2===a&&(b.navigationUI="show");a=document.documentElement;a.requestFullscreen?a.requestFullscreen(b):a.mozRequestFullScreen?a.mozRequestFullScreen(b):a.msRequestFullscreen?a.msRequestFullscreen(b):a.webkitRequestFullScreen&&("undefined"!==typeof Element.ALLOW_KEYBOARD_INPUT?a.webkitRequestFullScreen(Element.ALLOW_KEYBOARD_INPUT):
a.webkitRequestFullScreen())}}],["exit-fullscreen",()=>{"windows-webview2"===this.u||"macos-wkwebview"===this.u?(self.ma.Hb(!1),this.A.Hc({type:"set-fullscreen",fullscreen:!1})):document.exitFullscreen?document.exitFullscreen():document.mozCancelFullScreen?document.mozCancelFullScreen():document.msExitFullscreen?document.msExitFullscreen():document.webkitCancelFullScreen&&document.webkitCancelFullScreen()}],["set-hash",a=>{location.hash=a.hash}]]);window.addEventListener("online",()=>{t(this,"online-state",
{isOnline:!0})});window.addEventListener("offline",()=>{t(this,"online-state",{isOnline:!1})});window.addEventListener("hashchange",()=>{t(this,"hashchange",{location:location.toString()})});document.addEventListener("backbutton",()=>{t(this,"backbutton")});"undefined"!==typeof Windows&&Windows.UI.Core.SystemNavigationManager.getForCurrentView().addEventListener("backrequested",a=>{a.handled=!0;t(this,"backbutton")})}yc(f){alert(f.message)}Dc(f){f=f.isFocus;if("nwjs"===this.u){const a="nwjs"===this.u?
nw.Window.get():null;f?a.focus():a.blur()}else f?window.focus():window.blur()}});"use strict";async function aa(f,a){a=a.type;let b=!0;0===a?b=await ba():1===a&&(b=await ca());t(f,"permission-result",{type:a,result:b})}async function ba(){if(!self.DeviceOrientationEvent||!self.DeviceOrientationEvent.requestPermission)return!0;try{return"granted"===await self.DeviceOrientationEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request orientation permission: ",f),!1}}
async function ca(){if(!self.DeviceMotionEvent||!self.DeviceMotionEvent.requestPermission)return!0;try{return"granted"===await self.DeviceMotionEvent.requestPermission()}catch(f){return console.warn("[Touch] Failed to request motion permission: ",f),!1}}self.ma.Ra(class extends self.Ca{constructor(f){super(f,"touch");F(this,"request-permission",a=>aa(this,a))}});
